apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-common-config
  namespace: resume
data:
  KAFKA_BOOTSTRAP_SERVERS: "resume-kafka:9092"
  AUTH_ISSUER_URI: "http://resume-gateway:8080"
  PROFILE_SERVICE_URL: "http://resume-profile-service:8082"
  ELASTICSEARCH_URL: "http://resume-elasticsearch:9200"
  AUTH_CLIENT_ID: "resume-spa"
  AUTH_REDIRECT_URI: "http://localhost:4200/auth/callback"
  AUTH_POST_LOGOUT_REDIRECT_URI: "http://localhost:4200/"
  APP_CORS_ALLOWED_ORIGINS: "http://localhost:4200"
