apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config-common.yaml
  - config-mail.yaml
  - secret-internal.yaml
  - secret-auth-db.yaml
  - secret-outbox-db.yaml
  - secret-profile-db.yaml
  - secret-rabbitmq.yaml
  - secret-staticdata-db.yaml
  - secret-mail.yaml
  - uploads-pvc.yaml
  - auth-service.yaml
  - profile-service.yaml
  - search-service.yaml
  - staticdata-service.yaml
  - notification-service.yaml
  - outbox-relay-service.yaml
  - gateway-config.yaml
  - gateway.yaml
