apiVersion: v1
kind: Secret
metadata:
  name: resume-staticdata-db
  namespace: resume
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://resume-staticdata-db:5432/resume_staticdata"
  SPRING_DATASOURCE_USERNAME: "resume"
  SPRING_DATASOURCE_PASSWORD: "resume"
