apiVersion: v1
kind: Secret
metadata:
  name: resume-auth-db
  namespace: resume
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://resume-auth-db:5432/resume_auth"
  SPRING_DATASOURCE_USERNAME: "resume"
  SPRING_DATASOURCE_PASSWORD: "resume"
