apiVersion: v1
kind: Secret
metadata:
  name: resume-rabbitmq
  namespace: resume
stringData:
  RABBITMQ_HOST: "CHANGE_ME"
  RABBITMQ_PORT: "CHANGE_ME"
  RABBITMQ_USER: "CHANGE_ME"
  RABBITMQ_PASS: "CHANGE_ME"
