apiVersion: v1
kind: Secret
metadata:
  name: resume-outbox-auth-db
  namespace: resume
stringData:
  SPRING_DATASOURCE_URL: "CHANGE_ME"
  SPRING_DATASOURCE_USERNAME: "CHANGE_ME"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME"
