apiVersion: v1
kind: Secret
metadata:
  name: resume-profile-db
  namespace: resume
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://resume-profile-db:5432/resume_profile"
  SPRING_DATASOURCE_USERNAME: "resume"
  SPRING_DATASOURCE_PASSWORD: "resume"
