apiVersion: v1
kind: Secret
metadata:
  name: resume-messaging-db
  namespace: resume
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://resume-messaging-db:5432/resume_messaging"
  SPRING_DATASOURCE_USERNAME: "resume"
  SPRING_DATASOURCE_PASSWORD: "resume"
