server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: resume-search-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

app:
  cors:
    allowed-origins:
      - ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
  search:
    elasticsearch:
      enabled: true
    query-api:
      enabled: true
    profile-db:
      enabled: false
    indexing:
      enabled: true
